---
- name: Learn about hosts
  hosts: all

  tasks:
  - name: Classify hosts depending on their OS distribution
    group_by:
      key: os_{{ ansible_facts['distribution'] }}
  
  - name: Classify hosts depending on their system
    group_by:
      key: system_{{ ansible_facts['system'] }}

# - name: Set up macOS
#   hosts: os_MacOSX
#   gather_facts: False

#   tasks:


- name: set up Arch Linux installation as root
  hosts: os_Archlinux
  gather_facts: False
  become: yes

  tasks:
  - name: update pacman
    pacman:
      update_cache: yes
      upgrade: yes

  - name: install packages
    pacman:
      name:
        - dhcpcd
        - efibootmgr
        - fzf
        - git
        - grub
        - man
        - neovim
        - openssh
        - os-prober
        - python
        - sudo
        - vi
        - zsh
      state: present


- name: Set up home directory
  hosts: all
  gather_facts: False

  tasks:
  - name: Check if zsh is available
    command: grep -q zsh /etc/shells
    register: zsh_status
    failed_when: zsh_status.rc > 1

  - name: Download dotfiles
    git:
      repo: https://github.com/sakibc/dotfiles.git
      dest: ~/dotfiles
      update: no

  - name: create necessary directories
    file:
      path: "~/{{ item.path }}"
      state: directory
    loop:
      - { path: dotfiles/old }
      - { path: .config/nvim }

  - name: install base16 shell colour script
    git:
      repo: https://github.com/chriskempson/base16-shell.git
      dest: ~/.config/base16-shell

  - name: check for existing .bash_profile
    stat:
      path: ~/.bash_profile
    register: sym_bash_profile

  - name: get full path of dotfile .bash_profile
    stat:
      path: ~/dotfiles/bash_profile
    register: path_bash_profile

  - name: back up if exists non-symlink .bash_profile
    command: mv -f ~/.bash_profile ~/dotfiles/old/bash_profile
    when: >
      sym_bash_profile.stat.islnk is defined and
      (sym_bash_profile.stat.islnk == False or
      sym_bash_profile.stat.lnk_source != path_bash_profile.stat.path)
      
  - name: check for existing .zshrc
    stat:
      path: ~/.zshrc
    register: sym_zshrc

  - name: get full path of dotfile .zshrc
    stat:
      path: ~/dotfiles/zshrc
    register: path_zshrc

  - name: back up if exists non-symlink .zshrc
    command: mv -f ~/.zshrc ~/dotfiles/old/zshrc
    when: >
      sym_zshrc.stat.islnk is defined and
      (sym_zshrc.stat.islnk == False or
      sym_zshrc.stat.lnk_source != path_zshrc.stat.path)

  - name: symlink dotfiles
    file:
      src: '~/dotfiles/{{ item.src }}'
      dest: '~/{{ item.dest }}'
      state: link
    loop:
      - { src: bash_profile, dest: .bash_profile }
      - { src: init.vim, dest: .config/nvim/init.vim }
      - { src: login, dest: .login }
      - { src: tmux.conf, dest: .tmux.conf }
      - { src: zshrc, dest: .zshrc }

  - name: install Antigen
    script: ./shell_setup.sh
    args:
      creates: ~/.antigen.zsh

  - name: install vim plug
    script: ./vim_setup.sh
    args:
      creates: ~/.local/share/nvim/site/autoload/plug.vim


- name: set up Linux
  hosts: system_Linux
  gather_facts: False
  become: no

  vars:
    zsh_user: "{{ ansible_user_id }}"

  tasks:
  - name: change user shell to zsh
    become: yes
    user:
      name: "{{ zsh_user }}"
      shell: /bin/zsh