---
- name: Learn about hosts
  hosts: all

  tasks:
  - name: Classify hosts depending on their OS distribution
    group_by:
      key: os_{{ ansible_facts['distribution'] }}

- name: set up macOS development environment
  hosts: os_MacOSX
  roles:
    - macos
  tags:
    - init
    - macos

- name: set up Arch Linux installation
  hosts: os_Archlinux
  roles: 
    - archlinux
  tags:
    - init
    - archlinux

- name: set up Ubuntu development environment
  hosts: os_Ubuntu
  roles:
    - ubuntu
  tags:
    - init
    - ubuntu

- name: set up Ubuntu server on my desktop computer
  hosts: ubuntu_server
  roles:
    - ubuntu_server
  tags:
    - server_init
    - ubuntu

- name: set up octoprint on workshop
  hosts: octoprint
  roles:
    - octoprint
  tags:
    - octoprint
