---
- name: update pacman
  become: yes
  pacman:
    update_cache: yes
    upgrade: yes

- name: install system programs
  become: yes
  pacman:
    name:
      - python
      - python-pip
      - xdg-user-dirs
      - polkit
      - sudo
      - vi
      - nano
      - cmake
      - openssh
      - man
      - git
      - htop
    state: present

- name: install environment programs
  become: yes
  pacman:
    name:
      - base-devel
      - zsh
      - neovim
      - go
      - fzf
      - lynx
      - gpm
      - tmux
    state: present

# - name: install GRUB packages
  # become: yes
  # pacman:
    # name:
      # - efibootmgr
      # - grub
      # - os-prober
      # - intel-ucode
    # state: present
  # notify: "configure GRUB"

- name: set up common environment
  include_role:
    name: unix_env
    allow_duplicates: no

- name: set up Linux environment
  include_role:
    name: linux_env
    allow_duplicates: no

# - name: start systemd services
  # become: yes
  # systemd:
    # name: '{{ item.name }}'
    # enabled: yes
    # state: started
  # loop:
    # - { name: gpm }
